# Generated by Django 5.2 on 2025-04-15 02:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_initialprediction"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InitialPrediction",
            new_name="PromptPrediction",
        ),
    ]
