# Generated by Django 5.2 on 2025-04-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_rename_initialprediction_promptprediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptprediction",
            name="graph_state",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
