# Generated by Django 5.2 on 2025-04-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_promptprediction_graph_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promptprediction",
            name="graph_state",
            field=models.JSONField(null=True),
        ),
    ]
