# Generated by Django 5.2 on 2025-04-16 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_attributevalues"),
    ]

    operations = [
        migrations.CreateModel(
            name="SongPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song", models.JSONField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "graph_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.attributevalues",
                    ),
                ),
            ],
        ),
    ]
