# Generated by Django 5.2 on 2025-04-16 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_alter_songprediction_graph_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="songprediction",
            name="graph_state",
        ),
    ]
