# Generated by Django 5.2 on 2025-04-16 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_songprediction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songprediction",
            name="graph_state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predictions",
                to="api.attributevalues",
            ),
        ),
    ]
