# Generated by Django 5.2 on 2025-04-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_songprediction_graph_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="songprediction",
            name="song",
        ),
        migrations.AddField(
            model_name="songprediction",
            name="recommendation",
            field=models.TextField(null=True),
        ),
    ]
